spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://hmrs-postgres.c8fae2aue3id.us-east-1.rds.amazonaws.com:5432/postgres?sslmode=require
spring.jpa.properties.javax.persistence.validation.mode = none
spring.config.import=optional:aws-secretsmanager:hmrs/rds/prod
