name: ECS Rollback

on:
  workflow_dispatch:

jobs:

  rollback:

    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Rollback ECS Deployment
        run: |
          aws ecs update-service \
            --cluster hmrs-dev-cluster \
            --service hmrs-dev-service \
            --force-new-deployment
